version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: 'ordering_system'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      DATABASE_URL: mysql://admin:admin@db/ordering_system
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      timeout: 20s
      retries: 10
    networks:
      - backend_network
  backend:
    env_file:
      - .env
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    networks:
      - frontend_network
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
  backend_network:

volumes:
  static:
  frontend:
  mysql-data: