# Generated by Django 4.1.5 on 2024-06-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='table_id',
        ),
    ]
