# Generated by Django 4.1.5 on 2024-06-05 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_rename_table_order_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
