# Generated by Django 4.1.5 on 2024-06-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_order_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='table',
            new_name='table_id',
        ),
    ]
