# Generated by Django 4.1.5 on 2024-06-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
