# Generated by Django 4.1.5 on 2024-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_rename_table_invoice_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_flag',
            field=models.BooleanField(default=False),
        ),
    ]
