# Generated by Django 4.1.5 on 2024-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_order_done_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='done_flag',
        ),
        migrations.AddField(
            model_name='order',
            name='current_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
