# Generated by Django 4.1.5 on 2024-06-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_remove_order_done_flag_order_current_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
